name: Auto Process Icons
on:
  push:
    paths:
      - '*.png'
env:
  # 强制让 Action 运行在 Node 24 模式
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24 # 明确使用最新版
          
      - name: Install Sharp
        run: npm install sharp

      - name: Run process
        run: node process.js

      - name: Push Changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          if [ -n "$(git status --porcelain)" ]; then
            git commit -m "Fix naming conflict and sync icons"
            git push
          fi
